### ISSUE TITLE
CKAN Incompatibility with KSP 1.12.3.x

### ISSUE THREAD

**Issue by nblivin** [kna27/ksp-data-export#11]
I was looking to install KSP Data Export using CKAN, and it's not available for installation. After clearing the CKAN compatibility filter, I was able to find KSP Data Export in the mods list. The description states that the max KSP version for KSP Data Export is 1.12.2, and I'm running KSP 1.12.3.3173 (managed by Steam).

![image](https://user-images.githubusercontent.com/1562779/157344753-a21178e4-1f77-402b-938e-e3bdc9fea13e.png)

Is it possible to update the mod for compatibility with 1.12.3 to enable installation through CKAN?

**Comment by kna27** [comment]
Hey there! I updated the mod's metadata on spacedock, so it should be compatible with the latest KSP version on CKAN, please confirm if it works now. Thank you for reporting!

**Comment by nblivin** [comment]
![image](https://user-images.githubusercontent.com/1562779/157571016-bd7b5e5d-8d8e-4818-bd0b-69e786f22877.png)
The max game version now indicates 1.12.3. We're good to go. Thanks!
