### ISSUE TITLE
Thrust logged incorrectly at zero throttle setting

### ISSUE THREAD

**Issue by Krazy0** [kna27/ksp-data-export#14]
When a liquid fuel engine is set to zero throttle, it logs the full throttle thrust value. Also applies to TWR. 
Example graph: Skiff engine 
<img width="541" alt="thrust" src="https://user-images.githubusercontent.com/75238442/224530085-8ef30057-d72f-4b6d-ac53-896861f9c379.png">
CSV data file
[6c reentry 3_03111936.csv](https://github.com/kna27/ksp-data-export/files/10950217/6c.reentry.3_03111936.csv)

**Comment by kna27** [comment]
Hi,
Thanks for the bug reports. I'm a bit caught up with other projects right now but I'm looking into refactoring all the code for this project since it's currently a mess to work with. Hopefully I can get to this soon.
