### ISSUE TITLE
Data Extracting Fails upon Loading Two Crafts from Quicksave

### ISSUE THREAD

**Issue by Snugy321** [kna27/ksp-data-export#15]
Hello, I'm Snugy. I'd like to ask what happened to this mod whenever two craft files are loaded onto the same quicksave. I have extracted one of the craft's data, but now I want to record the other, to no avail. Can you please resolve this issue? Thank you in andvance!

**Comment by kna27** [comment]
Hi,
Thanks for opening an issue. Are you saying that you want to record another craft's information besides the one you are actively controlling? Or that trying to log information after quick-loading doesn't work?

**Comment by Snugy321** [comment]
It's sort of the former: I extracted data from an aircraft I'm working and then reverted to when the aircraft was in the runway. Then, I'd like to extract data from the already loaded rocket. It outputted nothing. 

This is the mod I've installed in my KSP, in case this is out of mod not playing nice with each other: 
1. Physics Range Extender
2. FAR
3. SXT Continued
4. BDArmory Continued
5. Automation Autopilot
6. ModuleManager
7. TweakScale

**Comment by kna27** [comment]
Okay, thanks for letting me know. I haven't worked on this project for a while but am planning on rewriting it completely to make it easier to work with and add new features sometime within the next three months, will also try and get this fixed in the rewrite as well.

**Comment by Snugy321** [comment]
Hello again. So, it turns out this applies to both cases. I was trying to record a rocket launch for a project of mine, and it didn't log the data. I hope this gets fixed as well with the rebuild
